let ac,sr,gn,is=0,curL=[],filtL=[],curI=-1,bpAb=null,curO={},curS=1,curT=14,maxW=0,trTi=null,trRem=0,trElap=0,trStopW=0,trDur=0,trIp=0,errs=[],oToks=[],uToks=[];
const $=(i)=>document.getElementById(i),au=$('au'),regs=[{u:"d82c26e4cb069d8f5b9d1f2a5cf42e24",t:"Eng"},{u:"363e6ce7f8e1b41be69bba7623c7c320",t:"Hin"}];
const clean=(s)=>s.replace(/[\u2018\u2019\u201c\u201d]/g,"'").replace(/[\u2013\u2014]/g,"-").trim();
const bare=(s)=>clean(s).toLowerCase().replace(/[.।!?;:,|]/g,'');
const tok=(t)=>{let r=[],re=/\S+/g,m;while((m=re.exec(t))!==null)r.push({t:m[0],s:m.index,e:re.lastIndex});return r};

function upWC(){const t=$('tx').value.trim(),l=$('lg').value;let w=0;if(t){if(l==='s')w=t.replace(/\s/g,'').length/5;else if(l==='p'){const tk=t.split(/\s+/);let sm=0,lg=0;tk.forEach(x=>{if(x.match(/[,;]/))sm++;if(x.match(/[.?!|\u0964]/))lg++});w=tk.length+(sm*0.5)+(lg*1)}else w=t.split(/\s+/).length}$('wc').value=Math.ceil(w);$('st').textContent='W: '+Math.ceil(w)}

function init(){
    regs.forEach(r=>{let o=document.createElement('option');o.value=r.u;o.textContent=r.t;$('rg').appendChild(o)});
    [40,50,60,80,90,100,120,140,160,180,200].forEach(v=>{let o=document.createElement('option');o.value=v;o.textContent=v;$('ws').appendChild(o)});
    [0.8,1,1.2,1.5].forEach(v=>{let o=document.createElement('option');o.value=v;o.textContent=v;$('rs').appendChild(o)});
    $('rg').onchange=e=>lG(e.target.value);
    $('f').onchange=e=>Array.from(e.target.files).forEach(f=>f.type.includes('audio')?(au.src=URL.createObjectURL(f),meta(f.name)):(r=new FileReader(),r.onload=v=>{$('tx').value=v.target.result;upWC()},r.readAsText(f)));
    lG(null);
}

function setP(v){const[min,max]=v.split('-');uSl('min',min);uSl('max',max==='max'?maxW:max)}
function uSl(t,v){let val=parseInt(v)||0;if(t==='min'){$('wMin').value=val;$('slMi').value=val}else{$('wMax').value=val;$('slMa').value=val}renL()}
function adj(k,v){if(k==='sc'){curS=Math.max(0.5,Math.min(1.5,curS+v));document.documentElement.style.setProperty('--sc',curS)}else{curT=Math.max(10,Math.min(48,curT+v));document.documentElement.style.setProperty('--ts',curT+'px')}}
function openM(){$('md').classList.toggle('active')}
async function lG(u){let list=[];try{for(let r of(u?[regs.find(x=>x.u===u)]:regs)){const res=await fetch(`https://gist.githubusercontent.com/vs-parihar/${r.u}/raw?t=${Date.now()}`);const j=await res.json();if(Array.isArray(j))list=list.concat(j.map(i=>({...i,reg:r.t})))}}catch(e){}lD(list);renT();renL()}
function lD(list){maxW=0;curL=list.map((i,idx)=>{let m=i.title.match(/WORDS\s*(\d+)/i),w=i.w||[],b=Math.max(...w,m?parseInt(m[1]):0);if(b>maxW)maxW=b;return{...i,_id:idx,maxW:b,tags:(i.tags||[]).map(t=>t.toUpperCase())}});$('slMi').max=$('slMi').value=$('slMa').max=$('slMa').value=maxW;uSl('min',0);uSl('max',maxW)}
function gW(i){const l=$('lg').value;if(i.w){if(l==='s')return i.w[0];if(l==='sp')return i.w[1];return i.w[2]}return i.maxW||0}
function renT(){const t=$('tags'),set=new Set();curL.forEach(i=>i.tags.forEach(g=>set.add(g)));t.innerHTML='';Array.from(set).sort().forEach(g=>{let s=document.createElement('span');s.className='filter-chip';s.textContent=g;s.onclick=()=>{s.classList.toggle('active');renL()};t.appendChild(s)})}
function renL(){const mi=parseInt($('wMin').value)||0,ma=parseInt($('wMax').value)||maxW,at=Array.from(document.querySelectorAll('.filter-chip.active')).map(x=>x.textContent),so=$('srt').value;filtL=curL.filter(i=>{const v=gW(i);return(v>=mi&&v<=ma)&&(at.length===0||at.every(t=>i.tags.includes(t)))});if(so==='on')filtL.sort((a,b)=>a._id-b._id);if(so==='no')filtL.sort((a,b)=>b._id-a._id);if(so==='az')filtL.sort((a,b)=>a.title.localeCompare(b.title));if(so==='sl')filtL.sort((a,b)=>gW(a)-gW(b));if(so==='ls')filtL.sort((a,b)=>gW(b)-gW(a));if(so==='sh'){for(let i=filtL.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[filtL[i],filtL[j]]=[filtL[j],filtL[i]]}}$('ls').innerHTML='';filtL.forEach((i,idx)=>{let d=document.createElement('div');d.className='list-item';d.innerHTML=`<div style="font-weight:500">${i.title}</div><div style="font-size:9px;color:#888">${gW(i)} words • ${fT(i.dur||0)}</div>`;d.onclick=()=>lA(i,idx);$('ls').appendChild(d)})}
async function lA(i,idx){curI=idx;curO=i;openM();$('tx').value="Loading...";const v=gW(i);if(v){$('wc').value=v;$('st').textContent='W: '+v;if(i.dur){$('wi').value=(v/(i.dur/60)).toString();$('ri').value="1.0000";sync('r')}}const id=i.url?.split('details/')[1],dl=`https://archive.org/download/${id}/`;let auSrc=i.audio;try{if(id){const mr=await fetch(`https://archive.org/metadata/${id}`),md=await mr.json(),fs=md.files||[];const mf=fs.find(f=>f.name.endsWith('.mp3')),of=fs.find(f=>f.name.match(/\.(wav|m4a|ogg|aac)$/i)),tf=fs.find(f=>f.name.endsWith('.txt')||f.name.endsWith('.md'));if(mf)auSrc=dl+mf.name;else if(of)auSrc=dl+of.name;if(i.matter){const r=await fetch(i.matter);$('tx').value=await r.text()}else if(tf){const r=await fetch(dl+tf.name);$('tx').value=await r.text()}else{$('tx').value=md.metadata.description?.replace(/<[^>]*>?/gm,'')||"No text"}}}catch(e){if(!i.matter)$('tx').value="Text Load Fail"}au.src=auSrc;au.load();upWC()}

function sync(s){const w=parseFloat($('wc').value),m=au.duration/60;if(!m||!w)return;if(s==='w'){$('ri').value=(parseFloat($('wi').value)/(w/m)).toFixed(4);au.playbackRate=Math.max(0.1,parseFloat($('ri').value))}else{const wpm=((w/m)*parseFloat($('ri').value));$('wi').value=(wpm%1===0)?wpm.toString():wpm.toFixed(2);au.playbackRate=Math.max(0.1,parseFloat($('ri').value))}const ws=$('ws'),wv=$('wi').value;ws.value=[...ws.options].some(o=>o.value===wv)?wv:""}
function dS(k,v){if(!v)return;if(k==='w')$('wi').value=v;else $('ri').value=v}
function adW(d){$('wi').value=(Math.round(parseFloat($('wi').value||0))+d).toString();sync('w')}
function adR(d){$('ri').value=(parseFloat($('ri').value||1)+d).toFixed(4);sync('r')}
function upV(){if(gn)gn.gain.value=$('vl').value}
$('wi').oninput=()=>sync('w');$('ri').oninput=()=>sync('r');
$('pl').onclick=async()=>{if(!ac){ac=new(window.AudioContext||window.webkitAudioContext)();sr=ac.createMediaElementSource(au);gn=ac.createGain();sr.connect(gn);gn.connect(ac.destination);upV()}if(is){au.pause();is=0;$('pl').innerHTML='<svg viewBox="0 0 24 24"><path d="M8 5v14l11-7z"/></svg>';$('pl').classList.remove('pausing')}else{if($('bp').checked&&au.currentTime<0.5){bpAb=new AbortController();try{await beeps(bpAb.signal)}catch(e){return}}await ac.resume();au.play();is=1;$('pl').innerHTML='<svg viewBox="0 0 24 24"><path d="M6 19h4V5H6v14zm8-14v14h4V5h-4z"/></svg>';$('pl').classList.add('pausing')}};
$('sb').onclick=async()=>{if(bpAb)bpAb.abort();au.pause();au.currentTime=0;is=0;$('pl').innerHTML='<svg viewBox="0 0 24 24"><path d="M8 5v14l11-7z"/></svg>';$('pl').classList.remove('pausing')};
async function beeps(sig){for(let i=0;i<5;i++){if(sig.aborted)throw'ab';const o=ac.createOscillator(),g=ac.createGain();o.connect(g);g.connect(ac.destination);g.gain.value=0.05;o.frequency.value=i===4?880:440;o.start();o.stop(ac.currentTime+0.1);await new Promise(r=>setTimeout(r,1000))}}
function sk(s){au.currentTime+=s}
au.ontimeupdate=()=>{if(!au.duration)return;const d=au.duration,c=au.currentTime,p=(c/d)*100,w=parseFloat($('wi').value)||150,lagS=(20/w)*60,effD=d-lagS*2,relC=Math.max(0,c-lagS),relP=effD>0?Math.min(100,relC/effD*100):p;$('pf').style.width=p+'%';$('tm').textContent=`${fT(c/au.playbackRate)}/${fT(d/au.playbackRate)}`;if($('as').checked){const m=$('tx').scrollHeight-$('tx').clientHeight;$('tx').scrollTop=(relP/100)*m}};
function fT(s){const m=Math.floor(s/60),x=Math.floor(s%60);return`${m}:${x<10?'0':''}${x}`}
$('pb').onclick=e=>{const r=$('pb').getBoundingClientRect();au.currentTime=((e.clientX-r.left)/r.width)*au.duration};
async function expA(){const b=$('exB'),r=parseFloat($('ri').value),id=curO.url?.split('details/')[1],dl=`https://archive.org/download/${id}/`;let srcU=au.src;b.classList.add('exporting');b.innerText='⌛';if(id){try{const mr=await fetch(`https://archive.org/metadata/${id}`),md=await mr.json(),fs=md.files||[];const bf=fs.find(f=>f.name.endsWith('.wav'))||fs.find(f=>f.name.endsWith('.flac'))||fs.find(f=>f.name.endsWith('.m4a'))||fs.find(f=>f.name.endsWith('.mp3'));if(bf)srcU=dl+bf.name}catch(e){}}try{const res=await fetch(srcU),buf=await res.arrayBuffer(),ctx=new OfflineAudioContext(2,buf.byteLength/r,44100),sBuf=await ctx.decodeAudioData(buf),src=ctx.createBufferSource();src.buffer=sBuf;src.playbackRate.value=r;src.connect(ctx.destination);src.start();const ren=await ctx.startRendering(),blob=new Blob([toWav(ren)],{type:'audio/wav'}),name=`${(curO.title||'audio').replace(/WPM\d+/i,'')}WPM${Math.round($('wi').value)}`;const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name+'.wav';a.click();const tBlob=new Blob([$('tx').value],{type:'text/plain'}),tA=document.createElement('a');tA.href=URL.createObjectURL(tBlob);tA.download=name+'.txt';tA.click()}catch(e){}finally{b.classList.remove('exporting');b.innerText='⬇️'}}
function toWav(b){let n=b.numberOfChannels,len=b.length*n*2+44,buf=new ArrayBuffer(len),v=new DataView(buf),pos=0,s=(st,s)=>{for(let i=0;i<s.length;i++)v.setUint8(st+i,s.charCodeAt(i))};s(0,'RIFF');v.setUint32(4,len-8,true);s(8,'WAVE');s(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,n,true);v.setUint32(24,b.sampleRate,true);v.setUint32(28,b.sampleRate*n*2,true);v.setUint16(32,n*2,true);v.setUint16(34,16,true);s(36,'data');v.setUint32(40,len-44,true);pos=44;for(let i=0;i<b.length;i++)for(let c=0;c<n;c++){let x=Math.max(-1,Math.min(1,b.getChannelData(c)[i]));v.setInt16(pos,x<0?x*0x8000:x*0x7FFF,true);pos+=2}return buf}
function opTr(){if(!$('tx').value.trim()){return}$('trM').classList.add('active');resTr();$('trS').disabled=0}
function clTr(){if(trIp)return;$('trM').classList.remove('active')}
function resTr(){trIp=0;clearInterval(trTi);$('trI').value='';$('trI').disabled=1;$('trS').disabled=0;$('trCD').textContent='00:00';$('trV').style.display='flex';$('rsV').style.display='none';$('trInf').textContent='Ready'}
function stTr(){const v=parseFloat($('trT').value)||parseFloat($('trC').value)||0;trStopW=(v===0);trDur=v*60;trRem=v*60;trElap=0;trIp=1;$('trI').disabled=0;$('trI').value='';$('trI').focus();$('trS').disabled=1;clearInterval(trTi);trTi=setInterval(()=>{if(trStopW)trElap++;else trRem--;let t=trStopW?trElap:trRem,m=Math.floor(t/60),s=t%60;$('trCD').textContent=`${m}:${s<10?'0':''}${s}`;if(!trStopW&&trRem<=0)subTr()},1000)}
function subTr(){clearInterval(trTi);trIp=0;$('trI').disabled=1;oToks=tok($('tx').value);uToks=tok($('trI').value);const m=oToks.length,n=uToks.length,dp=Array.from({length:m+1},()=>new Int32Array(n+1));const hs={'में':'मैं','मैं':'में','की':'कि','कि':'की','ओर':'और','और':'ओर','है':'हैं','हैं':'है'};for(let i=1;i<=m;i++)for(let j=1;j<=n;j++){const bo=bare(oToks[i-1].t),bu=bare(uToks[j-1].t);dp[i][j]=(bo===bu||hs[bo]===bu)?dp[i-1][j-1]+1:Math.max(dp[i-1][j],dp[i][j-1])}let i=m,j=n;errs=[];while(i>0||j>0){const bo=i>0?bare(oToks[i-1].t):'',bu=j>0?bare(uToks[j-1].t):'';if(i>0&&j>0&&(bo===bu||hs[bo]===bu)){const o=clean(oToks[i-1].t),u=clean(uToks[j-1].t);if(o!==u){let ty='h';errs.unshift({t:ty,o:oToks[i-1],u:uToks[j-1],i:i-1,j:j-1,ok:1})}else errs.unshift({t:'w',o:oToks[i-1],u:uToks[j-1],i:i-1,j:j-1,ok:1});i--;j--}else if(j>0&&(i===0||dp[i][j-1]>=dp[i-1][j])){errs.unshift({t:'f',u:uToks[j-1],j:j-1,i:-1});j--}else{errs.unshift({t:'m',o:oToks[i-1],i:i-1,j:-1});i--}}$('trV').style.display='none';$('rsV').style.display='flex';$('rS').value=$('tx').value;renCheckV();reCalc()}
function renCheckV(){const v=$('checkV');v.innerHTML='';errs.forEach(e=>{let s=document.createElement('span');if(e.t==='f')s.className='c-ins';else if(e.t==='m')s.className='c-mis';else if(e.t==='h')s.className='c-sp';else if(e.t==='d')s.className='c-dbl';s.textContent=(e.u?e.u.t:e.o.t)+' ';v.appendChild(s)})}
function reCalc(){let f=0,h=0,d=0,tot=oToks.length,isD=$('dblE').value==='1';errs.forEach(e=>{if(e.t==='f'||e.t==='m')f++;else if(e.t==='h')h++;else if(e.t==='d')d++});const cF=f*(isD?2:1),cD=d*2,erP=((cF+cD+(h/2))*100)/tot,acc=Math.max(0,100-erP),mx=parseFloat($('mxM').value)||100,obt=mx*(acc/100);$('resSc').innerHTML=`<span style="color:var(--re)">E: ${erP.toFixed(1)}%</span> | <span style="color:var(--gr)">A: ${acc.toFixed(1)}%</span> | <b>M: ${obt.toFixed(1)}</b>`;const l=$('eL');l.innerHTML='';errs.forEach((e,k)=>{if(e.t==='w'||e.t==='x')return;const it=document.createElement('div');it.className='e-it';it.innerHTML=`<div class="row" style="margin:0"><span class="e-ctx">${getCtx(oToks,e.i,2,-1)}</span><span class="e-w ${e.t==='f'?'m-err':(e.t==='h'?'m-h':(e.t==='d'?'m-d':'m-mis'))}" onclick="jump(${k})">${e.t==='m'?e.o.t:e.u.t}</span><span class="e-ctx">${getCtx(oToks,e.i,2,1)}</span></div><div class="row" style="margin-top:2px"><button class="xs-btn" onclick="upEr(${k},'f')" style="border-color:var(--re)">F</button><button class="xs-btn" onclick="upEr(${k},'h')" style="border-color:var(--bd)">H</button><button class="xs-btn" onclick="upEr(${k},'d')" style="border-color:var(--re)">D</button><button class="xs-btn" onclick="upEr(${k},'x')">X</button></div>`;l.appendChild(it)})}
function getCtx(tk,idx,c,dir){if(idx<0)return"";let s=[],cnt=0,curr=idx+dir;while(cnt<c&&curr>=0&&curr<tk.length){if(dir<0)s.unshift(tk[curr].t);else s.push(tk[curr].t);curr+=dir;cnt++}return s.join(' ')}
function jump(k){const e=errs[k],rs=$('rS'),cv=$('checkV'),sp=cv.children[k];if(e.o){rs.focus();rs.setSelectionRange(e.o.s,e.o.e);rs.scrollTop=(rs.scrollHeight*(e.o.s/rs.value.length))-(rs.clientHeight/2)}if(sp){sp.scrollIntoView({behavior:'smooth',block:'center'});[...cv.children].forEach(c=>c.style.outline='none');sp.style.outline='1px solid var(--in)'}}
function upEr(k,t){errs[k].t=t;reCalc();renCheckV()}
function refine(){$('rsV').style.display='none';$('trV').style.display='flex';$('trI').disabled=0;$('trI').focus()}
window.onload=init;
